-- Retired (#679). The canonical Darkly Suite D1 schema now lives in a single
-- authoritative file: packages/landing-shared/d1/schema.sql
--
-- This copy had drifted from the shared one in both directions (it lacked
-- licenses.stripe_status, idx_licenses_email, the user_sessions table, and
-- webhook_events; the shared copy lacked discount_code_usages and the
-- discount_codes active/max_uses/use_count columns). Those were reconciled
-- into the shared file as the canonical superset. Apply schema changes there.
